repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  wait: true
  timeout: 300

releases:
  - name: postgres
    namespace: default
    chart: bitnami/postgresql
    version: 10.4.6
    secrets:
      - secrets.yaml

  - name: django-todo
    namespace: default
    chart: ./helm/django-todo
    version: 0.1.0
    values:
      - postgresqlHost: postgres-postgresql
    secrets:
      - secrets.yaml
