{{- if .Values.ingress.create -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "django-todo.fullname" . }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels: {{ include "django-todo.labels" . | indent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "django-todo.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end -}}
