apiVersion: v1
kind: Secret
metadata:
  name: {{ template "django-todo.fullname" . }}-secret
  namespace: {{ template "django-todo.namespace" . }}
  labels: {{ include "django-todo.labels" . | indent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secretKey | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresqlPassword | b64enc | quote }}
