{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "django-todo.fullname" . }}
  namespace: {{ template "django-todo.namespace" . }}
  labels: {{ include "django-todo.labels" . | indent 4 }}
{{- end -}}
